DROP PROCEDURE sp_inserta_reg_rechazo;
CREATE PROCEDURE sp_inserta_reg_rechazo(
   p_fechaTramiteApp               CHAR(10),
   p_aplicacionOrigen              CHAR(2),
   p_claveAdminTransferente        CHAR(3),
   p_claveAdminReceptora           CHAR(3),
   p_fechaFirmaSolicitud           CHAR(10),
   p_folioSolicitudTraspaso        CHAR(10),
   p_fechaProbableLiquiTrasp       CHAR(10),
   p_tipoNotificacion              SMALLINT,
   p_motivoCancelacion             SMALLINT,
   p_nssTrabajador                 CHAR(11),
   p_curpTrabajador                CHAR(18),
   p_apellidoPaterno               CHAR(40),
   p_apellidoMaterno               CHAR(40),
   p_nombre                        CHAR(40),
   p_fechaNacTrabajador            CHAR(10),
   p_generoTrabajador              CHAR(1),
   p_entidadFederativaNac          CHAR(2),
   p_nacionalidad                  CHAR(3),
   p_rfcTrabajador                 CHAR(13),
   p_origenTipoTraspaso            SMALLINT,
   p_fechaPrimerRegistro           CHAR(10),
   p_fechaAltaAforeActual          CHAR(10),
   p_fechaAltaUltimoTraspComercial CHAR(10),
   p_indicadorPortabilidad         SMALLINT,
   p_ocupacionProfesionTrab        CHAR(2),
   p_actividadGiroNegocioTrab      CHAR(2),
   p_nivelEstudioTrab              CHAR(2),
   p_idProcesoExpe                 SMALLINT,
   p_calle                         CHAR(65),
   p_numeroExterior                CHAR(15),
   p_numeroInterior                CHAR(15),
   p_colonia                       CHAR(65),
   p_ciudadPoblacion               CHAR(65),
   p_delegacion                    CHAR(65),
   p_codigoPostal                  CHAR(5),
   p_entidadFederativaDom          CHAR(2),
   p_pais                          CHAR(3),
   p_telefonoMovil                 DECIMAL(10,0),
   p_telefonoFijo                  DECIMAL(10,0),
   p_extension                     CHAR(5),
   p_correoElecTrabajador          CHAR(50),
   p_fechaCertificacion            CHAR(15),
   p_tiposolicitud                 CHAR(2),
   p_nombreBeneficiario1           CHAR(40),
   p_apPaternoBeneficiario1	       CHAR(40),
   p_apMaternoBeneficiario1	       CHAR(40),
   p_curpBeneficiario1             CHAR(18),
   p_idCatParentesco1              CHAR(2),
   p_porcentajeBeneficiario1	     DECIMAL(5,2),
   p_nombreBeneficiario2           CHAR(40),
   p_apPaternoBeneficiario2	       CHAR(40),
   p_apMaternoBeneficiario2	       CHAR(40),
   p_curpBeneficiario2             CHAR(18),
   p_idCatParentesco2              CHAR(2),
   p_porcentajeBeneficiario2	     DECIMAL(5,2),
   p_nombreBeneficiario3           CHAR(40),
   p_apPaternoBeneficiario3	       CHAR(40),
   p_apMaternoBeneficiario3	       CHAR(40),
   p_curpBeneficiario3             CHAR(18),
   p_idCatParentesco3              CHAR(2),
   p_porcentajeBeneficiario3	     DECIMAL(5,2),
   p_nombreBeneficiario4           CHAR(40),
   p_apPaternoBeneficiario4	       CHAR(40),
   p_apMaternoBeneficiario4	       CHAR(40),
   p_curpBeneficiario4             CHAR(18),
   p_idCatParentesco4              CHAR(2),
   p_porcentajeBeneficiario4	     DECIMAL(5,2),
   p_nombreBeneficiario5           CHAR(40),
   p_apPaternoBeneficiario5	       CHAR(40),
   p_apMaternoBeneficiario5	       CHAR(40),
   p_curpBeneficiario5             CHAR(18),
   p_idCatParentesco5              CHAR(2),
   p_porcentajeBeneficiario5	     DECIMAL(5,2),
   p_respuesta_codRespuesta        CHAR(2),
   p_respuesta_codDiagnostico      SMALLINT,
   p_respuesta_descripcion         VARCHAR(100))

   -- se inserta registro con inconsistencia
   INSERT INTO afi_sol_trasp_app_rech VALUES(
      p_fechaTramiteApp,
      p_aplicacionOrigen,
      p_claveAdminTransferente,
      p_claveAdminReceptora,
      p_fechaFirmaSolicitud,
      p_folioSolicitudTraspaso,
      p_fechaProbableLiquiTrasp,
      p_tipoNotificacion,
      p_motivoCancelacion,
      p_nssTrabajador,
      p_curpTrabajador,
      p_apellidoPaterno,
      p_apellidoMaterno,
      p_nombre,
      p_fechaNacTrabajador,
      p_generoTrabajador,
      p_entidadFederativaNac,
      p_nacionalidad,
      p_rfcTrabajador,
      p_origenTipoTraspaso,
      p_fechaPrimerRegistro,
      p_fechaAltaAforeActual,
      p_fechaAltaUltimoTraspComercial,
      p_indicadorPortabilidad,
      p_ocupacionProfesionTrab,
      p_actividadGiroNegocioTrab,
      p_nivelEstudioTrab,
      p_idProcesoExpe,
      p_calle,
      p_numeroExterior,
      p_numeroInterior,
      p_colonia,
      p_ciudadPoblacion,
      p_delegacion,
      p_codigoPostal,
      p_entidadFederativaDom,
      p_pais,
      p_telefonoMovil,
      p_telefonoFijo,
      p_extension,
      p_correoElecTrabajador,
      p_fechaCertificacion,
      p_tiposolicitud,
      p_nombreBeneficiario1,
      p_apPaternoBeneficiario1,
      p_apMaternoBeneficiario1,
      p_curpBeneficiario1,
      p_idCatParentesco1,
      p_porcentajeBeneficiario1,
      p_nombreBeneficiario2,
      p_apPaternoBeneficiario2,
      p_apMaternoBeneficiario2,
      p_curpBeneficiario2,
      p_idCatParentesco2,
      p_porcentajeBeneficiario2,
      p_nombreBeneficiario3,
      p_apPaternoBeneficiario3,
      p_apMaternoBeneficiario3,
      p_curpBeneficiario3,
      p_idCatParentesco3,
      p_porcentajeBeneficiario3,
      p_nombreBeneficiario4,
      p_apPaternoBeneficiario4,
      p_apMaternoBeneficiario4,
      p_curpBeneficiario4,
      p_idCatParentesco4,
      p_porcentajeBeneficiario4,
      p_nombreBeneficiario5,
      p_apPaternoBeneficiario5,
      p_apMaternoBeneficiario5,
      p_curpBeneficiario5,
      p_idCatParentesco5,
      p_porcentajeBeneficiario5,
      p_respuesta_codRespuesta,
      p_respuesta_codDiagnostico,
      p_respuesta_descripcion);

END PROCEDURE
